language: node_js
node_js:
  - "6"

sudo: required

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml build --pull
  - docker-compose up -d redis celery rabbit

script:
  - docker-compose up app


