language: node_js
node_js:
  - "6"

sudo: required

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml pull
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml up -d redis celery rabbit

script:
  - docker-compose -f docker-compose.test.yml up app


