version: "2"
services:
  rabbit:
    image: rabbitmq
  redis:
    image: redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbit
      - redis
#    environment:
#      - CELERY_BROKER_URL=amqp://guest@rabbit:5672//
#      - CELERY_RESULT_BACKEND=redis://redis:6379/1
#      - CELERY_TASK_SERIALIZER=json
#      - CELERY_RESULT_SERIALIZER=json
  app:
    build: .
#    environment:
#      - CELERY_BROKER_URL=amqp://guest@rabbit:5672//
#      - CELERY_RESULT_BACKEND=redis://redis:6379/1
#      - CELERY_TASK_SERIALIZER=json
#      - CELERY_RESULT_SERIALIZER=json
    depends_on:
      - rabbit
      - redis

